services:
  postgres:
    image: postgres:16
    container_name: pulse_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: pulse_user
      POSTGRES_PASSWORD: pulse_pass
      POSTGRES_DB: pulse_db
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: pulse_rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"    # AMQP
      - "15672:15672"  # Management UI

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pulse_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  pgdata:
